### ISSUE TITLE
version 1.8.0 windows not install

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-desktop#101]
This version does not install on windows machine, it works for Mac. when we try to install it a series of green boxes appear

**Comment by noffle** [comment]
Thanks for the report, Aliya. I think something has broken a bunch of
the builds. I'll try and dig into this. Is this blocking you?

**Comment by aliya-ryan** [comment]
Hi - I think it’s fine but it means the Wao are using version 1.6.2 as that’s the last one that worked for them (I didn’t try them on the new ones). But I don’t think they’ve got any problems with it. 
Thanks for all the info - I’ll update to 1.9 once I’ve finished these maps and maybe do the same with the Wao when I’m with them.
Hope you have a great day,
A.

Aliya Ryan | Digital Democracy <http://digital-democracy.org/>  | UK: +44 (0)7518 454349 | aliya@digital-democracy.org
