### ISSUE TITLE
Add installer for Linux

### ISSUE THREAD

**Issue by HughP** [digidem/mapeo-desktop#113]
Electron works on Linux. Your product website says Mapeo works on MAC and PC, what about linux?

**Comment by noffle** [comment]
Hey @HughP. Yes, Mapeo runs just fine on Linux. You can get it running by following the README build instructions. We don't mention it on the website because we don't have an installer for it yet, nor published to any package managers.

**Comment by mir123** [comment]
+1 on this. I have installed in on my Linux box, would be fantastic to have an installer. This is important for us as we might use repurposed Chromebooks on our community forest mapping project in Panama.

**Comment by noffle** [comment]
@mir123 we're thinking the same thing! too many windows viruses to deal with. I'll try and make time for this. are you already using mapeo?

**Comment by mir123** [comment]
@noffle I'm testing it at home, we start field work later this month and ongoing this year. Very interested in checking out Mapeo and contributing to development. Can you drop me a line at mir at almanaqueazul decimal org?

**Comment by karissa** [comment]
There is now a linux installer in the form of an `AppImage` available on the latest Mapeo pre-release https://github.com/digidem/mapeo-desktop/releases/tag/v3.1.3

Feel free to let us know if you'd rather have other kinds of installers and we'll see to adding them
