### ISSUE TITLE
Sign with certificate on Windows

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#118]
For Mac see: https://github.com/digidem/mapeo-desktop/issues/115

The installer for Windows needs to be signed. On Windows the user is still able to open an unsigned app but on some systems will receive a warning that it is a security risk.

We need to buy a certificate for this. Some options are quite expensive. I would welcome ideas and suggestions about where to buy a cert and how to sign.

**Comment by arky** [comment]
There isn't an easy fix for this, Other than shelling out for a commercial vendor. The cheapest i could find was Comodo. 

Comodo ($179.95/yr)
https://www.comodo.com/landing/ssl-certificate/authenticode-signature/

Entrust ($299/yr)
https://www.entrustdatacard.com/products/digital-signing-certificates/code-signing-certificates

GoDaddy ($289.99/yr)
https://au.godaddy.com/web-security/code-signing-certificate

digicert ($474/yr)
https://www.digicert.com/code-signing/microsoft-authenticode.htm

**Comment by gmaclennan** [comment]
Thank you for this research @arky! What a pain we have to pay so much for this. I found a Comodo reseller, "Comodo SSL", which does seem legit, and is only $75 a year:

https://comodosslstore.com/codesigning.aspx

I will go ahead and purchase this soon and we can start code signing.

**Comment by gmaclennan** [comment]
Now fixed, [v4.1.0-beta.2](https://github.com/digidem/mapeo-desktop/releases/tag/v4.1.0-beta.2) and onwards should be signed on Windows
