### ISSUE TITLE
How do we record / store / visualise temporal data

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-desktop#121]
How do we show temporal / seasonal data on maps?

**Comment by noffle** [comment]
We don't currently. What kind of data are you thinking about Aliya?

**Comment by aliya-ryan** [comment]
This may well be something we manage within the presets, but I put it here as didn't want to forget about it. It's to do with being able to show a map of landuse in the summer for example, and another one for the winter - lots of indigenous people use territory differently at different times of year, but it's probably not so much to do with Mapeo and more to do with the presets and then styling.

**Comment by karissa** [comment]
I think you're right @aliya-ryan , let's say we handle this through presets/styling.
