### ISSUE TITLE
Mapeo 2.0.0 feedback

### ISSUE THREAD

**Issue by noffle** [digidem/mapeo-desktop#126]
1. I can't seem to zoom out to see the whole world anymore -- seems to be capped at 600 miles?
    - ~~[ ] Remove zoom-out cap~~ (addressed by gregor)
2. There are some regressions on the bottom-right status bar:
    - [x] Show Mapeo version not iD
    - ~~[ ] remove bug report icon~~ (addressed below)
    - [x] remove f user sillhouette icon
    - [x] remove logout link, to avoid confusion
3. The pre-submit screen for changesets when you click 'Save' after making edits seems to have some new UI. Thinking about things that could potentially be confusing / distracting to users:
    - [x] remove the text "The changes you upload as  will be visible on all maps that use OpenStreetMap data."?
    - [x] remove the "I would like someone to review my edits" checkbox
    - [x] We can probably also remove the "Add Field" box under the changeset description.
    - [x] Change the title "Upload to OpenStreetMap" to "Save Changes"?
    - [x] Change the "Upload" button to "Save"?
4. When you click "Upload" it shows another screen:
    - [x] Remove the share links
    - [x] Change the text to read "Congratulations, your edits have been saved to your local database. Synchronize to a USB drive to share your edits with others."
5. I tried the "Search Features" box that appears on app start for the first time: it seems to do an internet + OSM search for whatever you type in. It would be awesome if this did a p2p search one day!
    - [x] Remove search features box for now

Nothing *breaks*! This is awesome. I could be imagining it, but the interface feels a bit smoother. Awesome work on getting this all merged @karissa!

**Comment by gmaclennan** [comment]
This is really good feedback @noffle. @karissa I've changed the release to a preview release. I think we should get these kinks worked out before a full release.

**Comment by karissa** [comment]
* remove bug report icon: did not remove it. Instead, this is pointing to the github issues for mapeo-desktop

**Comment by karissa** [comment]
Also made it 'Congratulations, your edits have been saved. Synchronize to a USB drive to share your edits with others.' because 'local database' might be confusing

**Comment by karissa** [comment]
@gmaclennan said: "Regarding the 600 miles, it might be because one of the tools (point, line area) was selected when you were zooming? That seems to be a new limitation of iD v2, based on a min edit zoom setting."

**Comment by gmaclennan** [comment]
Interesting... when zooming with a mouse/trackpad scroll it is not possible to zoom all the way out, but using the zoom buttons it is possible.

This is an upstream bug, the current iD release has the same behaviour: http://preview.ideditor.com/release

On a brief search I do not see any existing issues for this, perhaps other users don't zoom out to the see the whole world much? Karissa can you file an upstream issue?

**Comment by karissa** [comment]
OK, opened an issue.

https://github.com/openstreetmap/iD/issues/4959
