### ISSUE TITLE
[hard to reproduce] zoom to data function not working correctly

### ISSUE THREAD

**Issue by karissa** [digidem/mapeo-desktop#136]

**Comment by noffle** [comment]
Oh no! What version? What is/isn't happening?

**Comment by karissa** [comment]
Latest. it zooms to the wrong place on the map.

**Comment by noffle** [comment]
How did you know it was the wrong place? Was there no data at all there? What dataset are you using?

**Comment by karissa** [comment]
It sent us to the middle of the Gulf of Mexico :P

He imported some of his own data using the Import GeoJSON feature, and then tried to Zoom to Data after that.

**Comment by karissa** [comment]
When zooming manually, the data was where it was expected to be.

**Comment by karissa** [comment]
Also, this was on Windows. Not able to reproduce here on my mac. It's possible the dataset he was using was strange. I can try to get ahold of it.

**Comment by noffle** [comment]
Hm. If you managed to get ahold of that geojson I could try and repro. :+1:

**Comment by karissa** [comment]
@noffle fixed this recently as now zoom to data does a density tile map to decide where to zoom
