### ISSUE TITLE
Can we make items show up with zoom farther out?

### ISSUE THREAD

**Issue by okdistribute** [digidem/mapeo-desktop#137]

**Comment by noffle** [comment]
It's possible, but I think @gmaclennan capped it because performance starts to chug with too much SVG on screen at once.

**Comment by karissa** [comment]
It was really confusing for a user at gaia amazonas today, he thought that the data wasn't loaded correctly!

**Comment by noffle** [comment]
Yeah it's really hard to find data. It was the motivation for the Zoom to Data feature actually! Once we get vector tiles working and a mapbox-gl layer in iD I think we'll be able to rig it up so we can see data from all zoom levels.

**Comment by karissa** [comment]
See github.com/digidem/mapeo-print-preview for details
