### ISSUE TITLE
GET /0.6/changeset/id returning 'Not Found' after changeset save

### ISSUE THREAD

**Issue by karissa** [digidem/mapeo-desktop#140]
Why?

**Comment by noffle** [comment]
Did you mean [GET /api/0.6/changeset/#id/download](https://wiki.openstreetmap.org/wiki/API_v0.6#Download:_GET_.2Fapi.2F0.6.2Fchangeset.2F.23id.2Fdownload)?

**Comment by karissa** [comment]
@noffle no was looking at Read: GET /api/0.6/changeset/#id

**Comment by karissa** [comment]
Weird, iD editor is trying to hit `/changeset/:id` instead of 0.6, not sure why. I don't see that anywhere in the spec, and they also have entries for `/history` which I'm not really sure is in the spec at all.

**Comment by karissa** [comment]
Updated to latest iD, if we still see this we can reopen
