### ISSUE TITLE
Cannot get offline tiles to work

### ISSUE THREAD

**Issue by LukasWillin** [digidem/mapeo-desktop#141]
I tried preparing offline imagery for mapeo as described in https://github.com/digidem/mapeo-desktop/blob/master/docs/offline_tiles.md.

Downloading was easy and just a matter of finding the ressources.

But making Mapeo aware of the tiles seems to just no work whatsoever. I tried several combinations of file names and folder structures and configurations in "imagery.json" and trying to scan the source code to find out what the application actually expects to no avail.

---
#### Environment:

- Windows 10
- Mapeo 2.1.0
- App Folder is in %APPDATA%/local/Mapeo

---
#### What I tried

I tried putting "imagery.json" and the "tiles" folder in different locations and restarting the app for the local server to load it. Tried different zooms while opening and closing the "layers" tab but the provider "local basel" never shows up.

---
#### Setup and Data used

The tiles used are created with the following command and picture Switzerland/Basel: 
`tile-dl -t "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}" --lon=7.6392227 --lat=47.552319 --radius 0.1 -z 12 -o {z}/{y}/{x}.jpg`

"imagery.json" contains the following definition:
`[
	{
		"name": "local basel",
		"type": "tms",
		"template": "http://localhost:5005/{zoom}/{y}/{x}.jpg",
		"scaleExtent": [ 0, 12 ],
		"overzoom": true,
		"default": false,
		"overlay": true
	}
]`

The Folder structure looks like this:
%APPDATA%/local/Mapeo/app-2.1.0/imagery.json
%APPDATA%/local/Mapeo/tiles/12/1429/2133.jpg

Did I miss anything?

**Comment by karissa** [comment]
If you don't see 'local basel' in the Mapeo imagery list, it's because it can't find the imagery.json file.  I suspect imagery.json needs to be at %APPDATA%/local/Mapeo/, thinking 'app-2.1.0' is preventing Mapeo from finding it.

**Comment by LukasWillin** [comment]
I have tried that as well but it didnt work. I tried it again maybe I forgot smth while changing directories

**Comment by LukasWillin** [comment]
Okay so I tried it again with the following structure:
%APPDATA%/local/Mapeo/imagery.json
%APPDATA%/local/Mapeo/tiles/12/1429/2133.jpg

I tried requesting a tile via Firefox and the mapeo developer tools:
http://localhost:5005/12/1429/2133.jpg
Answer is 404 "File not found :("
So the localhost is responding but cannot find the tiles...


Okay so I missed that Mapeo would use seperate Folders for the app and the settings.
Both the "tiles" folder and the imagery.json have to be in 
%APPDATA%/Roaming/Mapeo/imagery.json
%APPDATA%/Roaming/Mapeo/tiles/12/1429/2133.jpg
Maybe you want to include that in the readme.

So that sorted out I have a last question. I've noticed the option to "overzoom" the image but is there an option to "underzoom" it? Currently I only get the tiles to show when I am in the zoom range of 12 or higher.
Or is the only option here to download images for zoom levels 0 to 11?

**Comment by karissa** [comment]
sorry wasn't clear to me, did you fix the 404 issue?

You can download from zoom levels 0 to 11 if you change -z to 11, 10, 9, 8, 7 etc and put those folders in `tiles` too.

**Comment by LukasWillin** [comment]
Got it to work and the localhost:5005 is responding. Thank you very much :)
Okay then I download map tiles for the lower zoom levels.
I wish you a pleasant evening

**Comment by karissa** [comment]
Glad it's working out!

**Comment by noffle** [comment]
@LukasWillin glad you fixed it. Could you send a PR to this effect to update the document?

**Comment by LukasWillin** [comment]
@noffle 
Sure I will. I'll create one tomorror!

**Comment by LukasWillin** [comment]
@noffle
The PR is online.

Included:
1. Note about the folder structure on Windows
2. Windows Commands to execute Tile-DL
