### ISSUE TITLE
Larger data import (.shp) leaves mapeo in an unstable state

### ISSUE THREAD

**Issue by LukasWillin** [digidem/mapeo-desktop#153]
Good Day Digidem Dev Team

I wanted to preload some (fairly large) dataset in form of .shp-files:
But some of them left the application in an unstable state. The effects after the loading process finished were:

- Unable to save changes
- The imported shapes might not be visible again after a restart of mapeo
- Unable to import more data
- One might get a window at startup saying smth along the lines "recreating indexes" (but never finishes (I waited for around an hour))

The file in question can be downloaded here: [Dropbox - Sarawak Rivers (15.713mb)](https://db.tt/ZV9E8nx4is).
I have another file like this for multiple roads. Both files take around 1 hour to import.

I tried to make it work multiple times but always got into this state from which I cannot recover.

I tested these files on your latest commits as well.

Kind regards
Lukas

**Comment by karissa** [comment]
This should be fixed in 4.0.2 and above (forthcoming) let us know if that works for you @LukasWillin . You might need to wait a day or two until we release.

**Comment by LukasWillin** [comment]
Thank you so much for coming back to this issue. It is very appreciated!

Ill try it out in the next 1 or 2 week as I am currently unable to work on it
