### ISSUE TITLE
Offline maps in `xyz` format show in Mapeo, but tiles seem to be flipped

### ISSUE THREAD

**Issue by roblabs** [digidem/mapeo-desktop#155]
### Issue

* Actual behavior — Offline maps in `xyz` format show in Mapeo, but tiles seem to be flipped
* Expected behavior — PNG tiles imported into Mapeo should show with proper ordering

#### Research questions
* Are there assumptions about tiles coming in as `tms` or `xyz`?
* We tried `"type": "xyz",`. & `"type": "tms",`

### Background
We are working on methods to use offline PNG tiles with Mapeo. One idea was to extract PNG files that are stored as `mbtiles` and try to import those following the notes from https://github.com/digidem/mapeo-desktop/blob/master/docs/offline_tiles.md

#### Converting raster `mbtiles` for use in Mapeo 
The `mbtiles` utility, https://github.com/mapbox/mbutil, has schemes for converting from `.mbtiles` to either `xyz`, `tms` or `wms`.  

``` bash
# for command line parameters
mb-util -h 

# extract using the default parameters
mb-util bwcaw.mbtiles tiles/xyz
```

----
Figure 1 : Mapeo + offline tiles

##### Observations & Issues
* Tiles show in Mapeo
* Fetching PNG's via Mapeo port, `5005`, appears to be working, http://localhost:5005/xyz/14/4029/5692.png
* But the tiles don't stitch together properly and are out of order.  
* tile boundaries can be made out
* Note that the yellow UTM lines do not line up properly,
* the brown elevation lines do not align either

![screen shot 2018-06-02 at 2 31 37 pm](https://user-images.githubusercontent.com/118112/40881060-1047ea50-6672-11e8-98dc-3e10692bcc55.png)

----

#### `imagery.json`

* As noted in `offline_tiles.md`, this is needs to be an array.  This is what we used:

``` json
[
  {
    "name": "PNG tiles extracted from mbtiles",
    "type": "xyz",
    "template": "http://localhost:5005/xyz/{zoom}/{x}/{y}.png",
    "scaleExtent": [
      0,
      22
    ],
    "overzoom": true,
    "default": false,
    "overlay": true
  }
]
```

---
Figure 2 — Directory structure of where `imagery.json` is placed

![screen shot 2018-06-02 at 2 23 03 pm](https://user-images.githubusercontent.com/118112/40881169-29c1e8fc-6675-11e8-820c-87d7061f13d9.png)

**Comment by noffle** [comment]
Hey @roblabs. Thanks for the detailed report.

iD editor is responsible for interpreting the layer data and rendering it. I'm not sure why it's giving you difficulty. One think you might try is use the `tile-dl` example in the offline tiles notes, and see if that works. If it does, compare its tiles & fs layout to your own tiles and see if there's an obvious difference.

**Comment by karissa** [comment]
This should be fixed now in the latest version of Mapeo, along with the latest version of iD editor that allows you to choose in your custom background maps how to reference your xyz variables on the filesystem. please let us know if you still see this problem!
