### ISSUE TITLE
shadow migration to kappa-osm

### ISSUE THREAD

**Issue by noffle** [digidem/mapeo-desktop#161]
Rather than trying to coordinate switching **everyone** over to kappa-osm, we could do a *shadow migration* (nifty trick I learned at google):

1. modify mapeo-desktop to detect the old-style db on launch and generate a new kappa db with the same data
2. keep using the old osm-p2p-db for everything though!
3. all writes to the osm-p2p-db get shadow-written to the kappa db as well

This way we can build up kappa dbs of everyone's data, and be testing for reliability and correctness by periodically downloading and comparing the two to make sure they are still equivalent. Then at some point in the future we can release a mapeo-desktop that uses the kappa db by default instead, once we're sure everyone has an up-to-date local kappa db.

cc @gmaclennan @karissa

**Comment by karissa** [comment]
I think this is being punted for a direct migration strategy as far as I understand it. Right now it's external to mapeo-desktop, see digidem/mapeo-migrate
