### ISSUE TITLE
.deb installer

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#186]
**Describe the idea**
Add a `.deb` install package for Linux

**Additional context**
`AppImage` looks great and easy to use. However, I think for some users it could end up being confusing because:

1. Every time they download a new version they would save it somewhere, and probably not be good at cleaning up old versions, so they would end up with many copies around their filesystem.
2. A user could easily accidentally run an old version (see 1.) and get strange errors.
3. Users often expect to find this on the "start" menu on Linux desktop, or on the taskbar, and AppImage requires a manual process to set this up.
4. Updating the app would require manually updating menu and taskbar links.
5. AppImage seems to require a manual process to make it executable, which is a complicated step for some users.

`.deb` I think works well because:

1. The user can just double-click to install, and they get clear feedback about whether it is already installed.
2. We can create a menu shortcut at install time.
3. Updates will just work, replacing the previous version.

I think having both AppImage and .deb is good.

**Comment by mir123** [comment]
I've tested the .deb install on Linux Mint 19 and it works!

**Comment by karissa** [comment]
thanks @mir123 !
