### ISSUE TITLE
Namespaced discovery based on presets

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#205]
**Describe the idea**

A device only discovers other devices which share the same set of presets. E.g. if users from Sinangoe are on the same wifi network as users from Cuyabeno, and Sinangoe have a set of presets with the id `sinangoe`, and Cuyabeno have a set of presets with the id `cuyabeno`, then devices from Cuyabeno will only see other devices from Cuyabeno and only be able to sync with those.

**Comment by karissa** [comment]
Would this be handled by the concept of 'projects'?

**Comment by gmaclennan** [comment]
I think it can be, but I think there is an easier short-term solution. For Desktop we read a value called `dataset_id` from `metadata.json` in the presets, and use that to determine which sync file you can sync with. For mobile could we use this value to set the discovery id for wifi sync?

**Comment by okdistribute** [comment]
this is now implemented as `projectKey` in the presets
