### ISSUE TITLE
.deb installer shows incorrect metadata

### ISSUE THREAD

**Issue by okdistribute** [digidem/mapeo-desktop#219]
The stuff under 'details' is so wrong!
![Screenshot from 2019-05-30 14-19-33](https://user-images.githubusercontent.com/633012/58665559-ff11f780-82e5-11e9-9e10-1994298198b0.png)

**Comment by arky** [comment]
@karissa Unfortunately this bug cannot be resolved until the Ubuntu/Debian upstream issues with machine readable license file are fixed.  (See https://bugs.launchpad.net/ubuntu/+source/software-center/+bug/435183)

Recommend closing this bug as it can not be resolved in near future. :(

**Comment by arky** [comment]
@okdistribute  Guess this needs to be closed as invaild/wontfix

**Comment by okdistribute** [comment]
Thanks arky!
