### ISSUE TITLE
Gracefully handle errors in main process

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#22]
Right now an uncaught exception in the main process throws an unintelligible (to the user) error message, and quits the app, but leaves a process running in the background.

We need to handle this error, provide a custom error message, and gracefully quit the app.

This has been a problem when a bug pops up, we fix it, but a background electron process is still running (on windows) which maintains a lock on the osm-p2p-db, and needs to be quit manually.

Here are some guidelines about how to handle uncaught exceptions in Electron:

https://github.com/atom/electron/issues/2479

**Comment by karissa** [comment]
this should be fixed
