### ISSUE TITLE
Specify version in 'About' menu

### ISSUE THREAD

**Issue by okdistribute** [digidem/mapeo-desktop#223]
**Describe the bug**
The about menu is empty. Let's show the current mapeo version there.

**Additional context**
It might be also nice to have a link to the guide.mapeo.world documentation site that we are building!

**Comment by todrobbins** [comment]
I'll take this one!

**Comment by okdistribute** [comment]
We will close this because we added the version number to the bottom left of the screen! If you want to help more with stuff @todrobbins, let me know, happy to jump on a call and discuss :)
