### ISSUE TITLE
Mapeo-desktop doesn't work with NodeJS 10 / 12 

### ISSUE THREAD

**Issue by arky** [digidem/mapeo-desktop#228]
**Describe the bug**
Mapeo-desktop doesn't build with latest versions of NodeJS 10+ Some modules such as leveldown doesn't complete builds. See https://pastebin.com/PVHd1euk 

**Can you do the same thing twice?**
Install NodeJS 10 or later and run 'node install' 

**Desktop:**
 - OS: Ubuntu Comic 

**Additional context**
"/home/arky/.node-gyp/12.4.0/include/node/v8.h:2738:7: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/home/arky/.node-gyp/12.4.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/arky/.node-gyp/12.4.0/include/node/node_object_wrap.h:84:78:   required from here
/home/arky/.node-gyp/12.4.0/include/node/v8.h:9817:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
               reinterpret_cast<Callback>(callback), type);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/arky/.node-gyp/12.4.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:66:61:   required from here
/home/arky/.node-gyp/12.4.0/include/node/v8.h:9817:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [leveldown.target.mk:125: Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory '/media/arky/DevDrive/Code/Mapeo/mapeo-desktop/node_modules/osm-p2p-server/node_modules/leveldown/build'"

**Comment by okdistribute** [comment]
Is this still an issue?

**Comment by arky** [comment]
@okdistribute Testing with Node 12 on Windows 8. Works without any issues.

**Comment by okdistribute** [comment]
thanks @arky !
