### ISSUE TITLE
SMART (Spatial Monitoring and Reporting Tool) integration

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#244]
### Idea

Integration with [SMART](https://smartconservationtools.org) software. SMART is used by governments and conservation organizations for managing monitoring data and patrols of park guards. There is an accompanying mobile app [SMART Mobile](https://smartconservationtools.org/smart6/) built on [CyberTracker](https://www.cybertracker.org) for field data collection.

### Ideal workflow

Mapeo Mobile/Desktop can export monitoring data in a format that can be imported into SMART Desktop.

1. User exports observations from a recent trip
2. User imports file into SMART Desktop as a new patrol report
3. User views observations in SMART

This would require configuring presets in Mapeo to match the data model configured in SMART Desktop. It should be possible to write code to transform a Smart data model to presets automatically.

### Additional context

- SMART [data model docs](https://smartconservationtools.org/wp-content/uploads/2019/08/SMART%20Essentials%20Training%20Handbook_v1.0.pdf) (Section 2.6)
- SMART ["Patrol Package" for mobile](https://github.com/digidem/mapeo-desktop/files/3550676/smart-patrol-package.zip). It includes icons and an XML with field/question definitions and categories to show. This is what would need to be converted to presets.
- [SMART Mobile export](https://github.com/digidem/mapeo-desktop/files/3550679/CTDATA_00001_2019-08-27T15_01_39_Sighting.json.zip). This is a GeoJSON exported from SMART Mobile. Mapeo Mobile/Desktop could export this format for import into SMART.

**Comment by arky** [comment]
@gmaclennan This would be great feature for mapeo-desktop. :+1:

**Comment by gmaclennan** [comment]
@arky are you using SMART? Could you share a little about how you use it and what kind of integration would be useful?

**Comment by arky** [comment]
@gmaclennan I do long term photo documentary work with few conservation biologists. Some of them use SMART and other Android mobile apps for their work. ( See 
https://www.wildlabs.net/resources/case-studies/spatial-monitoring-and-reporting-tool-smart ) 

During one of my recent chats, one of them mentioned that they are looking at alternatives mobile interfaces to SMART mobile. 

Another oft asked feature request relate to communication between field patrols and central offices which GIS folks are usually based. For instance, a field ranger sends a location of an logging incident or encroachment to public lands back to central office for checking. At the moment such realtime communication is conducted via GSM calls or SMS when available.

**Comment by arky** [comment]
@gmaclennan I would recommended reach out to world-wide community on WildLabs (https://www.wildlabs.net/) for more feedback. 

I also plan to to gather and present some feature requests from the biologists in future as well.

**Comment by okdistribute** [comment]
Now you can export a SMART csv from the menu in the top right of the Observations screen. Let us know if that doesn't satisfy requirements?
