### ISSUE TITLE
Show Mapeo Version number in Filter Screen

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-desktop#248]
Currently the only way to see what version of Mapeo is installed is to switch to the Editor screen and it's visible in bottom right hand corner. As many of our partners are not using this screen it would make sense that there was somewhere on the Filter screen where the version number was visible or accessible.
It used to be visible by a 'about Mapeo' item if you went to top menu, but that isn't there any more.

**Comment by okdistribute** [comment]
Fixed with the redesign
