### ISSUE TITLE
Set encryption key to Project ID

### ISSUE THREAD

**Issue by noffle** [digidem/mapeo-desktop#250]
This is a TODO for once we get project IDs into Mapeo. It basically amounts to initializing `mapeo-core` with an opts like

`{ encryptionKey: projectId }`

**Comment by noffle** [comment]
One more TODO: pass opts = { internetDiscovery: true } into mapeo-core.

**Comment by noffle** [comment]
You'll also need the latest `osm-p2p` and `@mapeo/core` versions!

**Comment by okdistribute** [comment]
it's named projectKey now in the presets

**Comment by gmaclennan** [comment]
Closing because this was implemented in v5
