### ISSUE TITLE
Quitting app can break indexes

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#26]
Right now there are no checks on app quit, so writes to indexes could be cut off mid-write. We need to add some hooks to quitting the app to make sure everything is written to disk before we close down.

- [ ] Check indexing is complete before quit
- [ ] Batch index updates upstream

**Comment by substack** [comment]
This will catch some issues, but the app could also crash or the computer could run out of power, resulting in bad indexes. The more complete fix will involve making the indexes robust against interrupts. I think we can do this by doing batch updates in some places where we aren't currently doing that. In leveldb, batch updates are atomic, so one place to start is to add a batch update operation upstream in osm-p2p-db and then integrate this into the changeset handling in osm-p2p-server.

**Comment by karissa** [comment]
closed in mapeo 4
