### ISSUE TITLE
Remove or fix "Import map tiles" function from menu

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-desktop#261]
Not really a bug but this feature doesn't currently work so best remove it until it's fixed so users don't get confused (or fix it...).

Team knows about this but I wasn't sure if it was written down so logging here.

**Comment by okdistribute** [comment]
This was fixed in #262 if the user follows [the guide here](https://digital-democracy.gitbook.io/mapeo/custom-imagery), but I think there needs to be more extensive work done on how to make this easier for users.
