### ISSUE TITLE
Clicking on an observation breaks the Observation view

### ISSUE THREAD

**Issue by okdistribute** [digidem/mapeo-desktop#266]
**Describe the bug**
When I click on any of my observations, it shows the following error message:

```
Oh dear! An error has occurred
The details below will be useful for finding a way to fix this…


Error:
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `AutoSizer`.

Stacktrace:

    in div (created by AutoSizer)
    in AutoSizer (created by MediaCarousel)
    in div (created by MediaCarousel)
    in MediaCarousel (created by DialogContent)
    in div (created by DialogContent)
    in MuiPickersUtilsProvider (created by DialogContent)
    in DialogContent (created by ObservationDialog)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Dialog))
    in div (created by Transition)
    in Transition (created by ForwardRef(Fade))
    in ForwardRef(Fade) (created by TrapFocus)
    in TrapFocus (created by ForwardRef(Modal))
    in div (created by ForwardRef(Modal))
    in ForwardRef(Portal) (created by ForwardRef(Modal))
    in ForwardRef(Modal) (created by ForwardRef(Dialog))
    in ForwardRef(Dialog) (created by WithStyles(ForwardRef(Dialog)))
    in WithStyles(ForwardRef(Dialog)) (created by ObservationDialog)
    in ObservationDialog (created by WrappedMapView)
    in WrappedMapView (created by ForwardRef(MapView))
    in ForwardRef(MapView) (created by FilterVi
```

I see this in the console as well:

```
map.js:1676 Uncaught TypeError: Cannot read property 'getLayer' of undefined
    at r.getLayer (map.js:1676)
    at r.delegates.o.<computed> (map.js:922)
    at r.Bt.fire (evented.js:119)
    at HTMLDivElement.<anonymous> (bind
```

**Can you do the same thing twice?**
The exact steps to see the problem again.
1. Using the `bin/mock.js`, create some fake data points
2. Syncronize them to desktop.
3. Try to click on a point, and you'll see the crash

**Expected behavior**

**Desktop:**
 - OS: Linux

**Additional context**
This may be as simple as an issue with the data structure of the mock data, but hard to tell -- either way, it probably shouldn't panic & crash the whole Observations view if a single data point is malformatted somehow.

**Comment by marcoautiero** [comment]
I explored this issue but I didn't find anything wrong.

To be precise: I installed the app, I created some fake data points and I synchronized them to desktop; trying to click on a point I had the crash.

Then, I removed node_modules and I re-installed the app; from then on I didn't meet the crash anymore.

I'm trying different situations; please, could you tell me how to completely delete the mocked data? I also tried to delete the complete project (cloning and installing it again) but I always find in the app the previously mocked data. I would like to start from scratch, without them.

**Comment by okdistribute** [comment]
Hi @marcoautiero ! Good question. Data within the app is stored separately from the actual installer, so that data can persist between installs or in the case of an accident. I just updated the [README](https://github.com/digidem/mapeo-desktop#testing) with information about where the data is stored.

I think this bug was fixed in a newer version of MapFilter so perhaps we can close this -- I'm also not seeing the bug anymore.

Thanks for checking! If you want to discuss how to get more involved in Mapeo, I'd be happy to chat about that.. please reach out on our public IRC or slack (find those links at https://mapeo.world). We are ramping up our development again actively this year and would love more help!

~K
