### ISSUE TITLE
Incorrect peer render state

### ISSUE THREAD

**Issue by noffle** [digidem/mapeo-desktop#269]
I noticed this while working on something else: mapeo-core will bubble up peer state that says e.g. `replication-wifi-ready`, but the rendered state is `progress`.

![renderstate](https://user-images.githubusercontent.com/489362/73307114-6b752b80-41d2-11ea-9ea2-3546c40817ed.png)

**Comment by okdistribute** [comment]
Where is the 'replication-wifi-ready' coming from? If it's coming from `progress` event, thats getting caught and thrown away here: https://github.com/digidem/mapeo-desktop/blob/2a2fa5c3ed378a13a56c23027f3d6fbffb828170/src/main/server.js#L105

**Comment by okdistribute** [comment]
we plan to fix this in lower-level refactoring next month cc @noffle
