### ISSUE TITLE
Open STreet map labels still appearing

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-desktop#273]
Text referring to Open Street map still appears - using V5.0.0 of Mapeo Desktop:

1) in the Territory screen it is there when you hover over the save button; 

2) also on the screen that appears if you press that button to save changes; 

3) (not photo) also on the popup that appears momentarily when you are saving.

See photos.

![a1c8d8a1-9c1a-40b9-85ee-24e788fe0440](https://user-images.githubusercontent.com/21277147/73960642-4753d180-48d9-11ea-8e96-9638e934fa61.jpg)
![aa0be583-7f21-489b-a85f-c470c5d257a1](https://user-images.githubusercontent.com/21277147/73960645-4884fe80-48d9-11ea-821d-2bce71aacd49.jpg)

**Comment by okdistribute** [comment]
I will look at this soon!

**Comment by okdistribute** [comment]
Looking at the history, seems like @gmaclennan had thrown away some edits that we necessary to get this to work before, not sure if that was on purpose or on accident? Going to try to patch this up from an older branch.

**Comment by okdistribute** [comment]
Fixed in [id-mapeo v3.1.3 ](https://github.com/digidem/iD-mapeo/commit/bc32bdaf928b3d6b00baf81d9612d5081cdfd0f3)
