### ISSUE TITLE
Splash screen loading image

### ISSUE THREAD

**Issue by okdistribute** [digidem/mapeo-desktop#287]
When Mapeo loads, there is a splash screen that just has the Mapeo logo, but it seems to be low resolution (fuzzy around the edges) and the words 'Cargando...'

Ideally this splash screen would not have words (so they don't need to be translated into all the languages) but instead have a loading image that moves, like a GIF, that indicates progress (a spinner, maybe the logo spinning around and jumping or something fun like that?)

**Comment by arky** [comment]
For some reason the splash draws itself onto top other windows. You can not switch away using 'alt tab' on Windows
