### ISSUE TITLE
True multilingual build with base default settings, icon and categories translated

### ISSUE THREAD

**Issue by okdistribute** [digidem/mapeo-desktop#289]
Requested by @arky 

In the future, I think it would be very useful to have true multilingual
build with base default settings, icon and categories translated. This
would help people to start using mapeo quickly thus help us drive
adoption in the Southeast Asia. Also may be we can push
some local customization's from mapeo-desktop to mapeo-mobile.  These
things might reduce the barrier of entry even further.

Currently, the base default settings are created in the [mapeo-default-settings](github.com/digidem/mapeo-default-settings/) repository. Perhaps the fix here would be to put these into Crowdin or some other translation service as well.

**Comment by okdistribute** [comment]
https://github.com/digidem/mapeo-default-config/pull/1

**Comment by arky** [comment]
@okdistribute Trying to drive full localization of mapeo-suite into Thai, Vietnamese and Khmer. It would be great if you please kindly merge all translation strings into single Mapeo-desktop project on Crowdin https://crowdin.com/project/mapeo-desktop
