### ISSUE TITLE
Can't read property of 'x'

### ISSUE THREAD

**Issue by arky** [digidem/mapeo-desktop#306]
Mapeo-desktop (5.0.x) fails to start on Windows 10 64 bit machine. The program crashes with following JavaScript error. Setting debug flags doesn't generate much errors other than this dialog

![DSC_0144](https://user-images.githubusercontent.com/808895/76474883-abfdd100-642f-11ea-837a-9239cad6a330.JPG)

**Comment by okdistribute** [comment]
This should be fixed now, please re-open if you see it happen again.
