### ISSUE TITLE
[Docs] Micro Routers for offline WiFi Networks 

### ISSUE THREAD

**Issue by arky** [digidem/mapeo-desktop#307]
I think these new generation of Micro Routers (https://www.gl-inet.com/products/gl-usb150/) would be able provide offline wifi networks while being powered by usb powerbanks. 

Their small power consumption and ability to support upto 50 devices would outperform other routers or mobile hotpsots (mifi) devices. 

Plan to use these device in my field trails in southeast asia.

**Comment by okdistribute** [comment]
These are very cool. @jencastrodoesstuff has opinions about routers, what do you think?

**Comment by jencastrodoesstuff** [comment]
Very cool! Anything that helps reduce possible hardware or cable failures in the field.
