### ISSUE TITLE
chore: Organize code by process

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#325]
We currently have two folders under [`src`](https://github.com/digidem/mapeo-desktop/tree/master/src) called `main` and `renderer` which initially organized code by [process](https://www.electronjs.org/docs/tutorial/application-architecture#main-and-renderer-processes): code in the `main` folder ran in the main process, and code in the `renderer` folder ran in the renderer process.

We now have a new process, `background.js` which runs servers and mapeo-core.

It would be helpful for understanding the code to keep code organized by process, e.g. to move the code that runs in the background process into its own folder. I _think_ this includes `mapeo-ipc.js`, `mapeo.js`, `server.js`, and `osm-stats.js`.

**Comment by okdistribute** [comment]
Yes this makes sense..
