### ISSUE TITLE
Sync screen flickering 

### ISSUE THREAD

**Issue by okdistribute** [digidem/mapeo-desktop#328]
**Describe the bug**
After a certain series of steps, the sync screen flickers making it unusable/difficult to use. Like chasing a cat. Maybe a little funny at first but then it gets pretty annoying.

**Can you do the same thing twice?**
The exact steps to see the problem again.

0. Load preset A on desktop and mobile
1. Create some observations on mobile.
2. Open the sync screen.
3. Load preset B mobile. (obs. -> settings -> import configuration)
4. Load preset B on Desktop. (file -> import configuration)
5. Open the sync screen.

See no devices can be found.

6. Restart mapeo (desktop+mobile?)

Bug appears. 

**Expected behavior**
You should be able to load presets and sync afterward with no issues.

**Version**
2.1.0

**Additional context**
After restarting Mapeo Desktop, you still see the same behavior.

**Comment by noffle** [comment]
Could this be the same underlying bug as https://github.com/digidem/mapeo-core/issues/84? It'd be good to test this again once https://github.com/digidem/mapeo-core/pull/87 is merged.

**Comment by okdistribute** [comment]
Yeah that's right. This particular bug is reported to be fixed on master (v5.2.1) now -- by fixing the underlying error. The sync screen flickering will still pop up whenever there is an error reported, until the new code arrives.

**Comment by okdistribute** [comment]
To be completely fixed, we need to update to the latest mapeo-core v8 and then change the frontend to comply (similarly to mapeo-mobile)

**Comment by okdistribute** [comment]
fixed by #364
