### ISSUE TITLE
Update Mapeo automatically when a new version is available

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#34]
Mapeo should automatically update when it has an internet connection and a new version is available.

- [x] Download updates in the background and install on relaunch
- [x] Add UI to show whether an update is available, click to manual install + restart
- [x] Use delta updates to reduce download size
- ~[ ] Distribute updates over the p2p network~ (captured in mapeo-core#92)

**Comment by arky** [comment]
@okdistribute I thought we already have auto update feature working in mapeo-desktop?

**Comment by okdistribute** [comment]
No we don't unfortunately. This will be made priority this year.

**Comment by okdistribute** [comment]
relevant docs:
* https://www.electron.build/auto-update
* https://github.com/iffy/electron-updater-example

**Comment by okdistribute** [comment]
Currently dealing with bug where it says 'estimated download time 0 seconds'

**Comment by okdistribute** [comment]
This is how it'll look in 5.4, opening a new issue for improving the user interface!
![Screenshot from 2020-10-08 15-57-04](https://user-images.githubusercontent.com/633012/95521890-8ada7000-097f-11eb-897f-5d13f5ccda99.png)
![Screenshot from 2020-10-08 15-57-12](https://user-images.githubusercontent.com/633012/95521888-8ada7000-097f-11eb-8b0b-08e30463e62d.png)
![Screenshot from 2020-10-08 15-58-51](https://user-images.githubusercontent.com/633012/95521887-8a41d980-097f-11eb-8b41-d773258d1912.png)
![Screenshot from 2020-10-08 15-59-06](https://user-images.githubusercontent.com/633012/95521886-89a94300-097f-11eb-829e-1af31c3e5e26.png)
