### ISSUE TITLE
select_multiple fields uneditable

### ISSUE THREAD

**Issue by okdistribute** [digidem/mapeo-desktop#345]
**Can you do the same thing twice?**
1. Use select_multiple in your `.mapeosettings` file (if you're interested in working with this, we can give you a file to use)
2. Use it to collect some data in mobile. 
3. Syncronize with desktop
4. Go to 'observations', open an observation with select_multiple field
5. See the field greyed out and unselectable.

**Expected behavior**
The select_multiple fields should all be editable

**Additional Context**
This will require some thinking about the user experience design.

**Desktop:**
- 5.2.x 
![46f56710e9096718e6ebb0eec69e7c1b](https://user-images.githubusercontent.com/633012/81596369-ce04c880-9378-11ea-8a56-bfb3a6ec4dd6.jpg)

**Comment by okdistribute** [comment]
@thibautRe is this something you might be interested in tackling?

**Comment by thibautRe** [comment]
Hey @okdistribute, thank you for involving me!

I'd love to get back to contributing to Mapeo, my work/life balance is slowly getting back to normal and I can take some non-urgent tasks again :)

I haven't touched or work with the `.mapeosettings` file yet, I just know its existence and roughly what is does through the [documentation](https://docs.mapeo.app/customization/preparing-mapeo-configuration).

So if I can get access to a settings file that has the `select_multiple` attribute enabled I can start digging into the issue :)

**Comment by okdistribute** [comment]
Hi @thibautRe!

You actually could implement this without a `.mapeosettings` file now, in react-mapfilter v3 branch, using `npm run storybook` which has some dummy/test data for the multiselect!

https://github.com/digidem/react-mapfilter/tree/v3

Thanks so much for offering to help. We're a bit low on resources for front-end development at the moment. It's unclear how the interface should work, but perhaps looking at existing input designs could help since they've probably thought about it quite a lot. I suspect it would take a bit of space which could create some challenges with the ObservationEdit modal.

Another discussion we've had is changing the ObservationEdit screen from a modal to a full view that would take up more space, since users have reported that they don't like modals. We could also explore this if multiselect doesn't seem to fit well in the modal...

**Comment by thibautRe** [comment]
I looked a bit into the current solution.

Since `react-mapfilter` is using `@material-ui`, would it make sense to use Mui's `<Select multiple />` field directly? You can see it in action here https://material-ui.com/components/selects/#multiple-select

Also, was there a specific reason to use Downshift for the `<SelectOne />` component? It seems like using Mui's default `<Select />` would have worked fine there, but I might miss some context here.

**Comment by okdistribute** [comment]
cc @gmaclennan thoughts?

**Comment by okdistribute** [comment]
Conversation continuing on the above PR.
