### ISSUE TITLE
Sync Error - missing data time out

### ISSUE THREAD

**Issue by jencastrodoesstuff** [digidem/mapeo-desktop#368]
**Describe the bug**
Md is not completing sync process with any versions of Mm

**Can you do the same thing twice?**
Mostly replicable except for  one inconsistant sucessful attempt
1. Devives all using same project key
2. Go to 'Sync screen on mobile and desktop'
2. Devices recognize each other
3. hit sync
4. See errors: Sync stream terminated on remote side (v5) AND timed out due to missing data (v2)

Results:

- No data appears to sync in Md*
- Media files appear to be added to the kappa db folder. different media files with different sync attempts based on timestamps
* I have no idea how or when the media and points appeared. itthis only happened once out of multiple attempts with Mm v5
**Expected behavior**
files sync from Mm and are veiwable ++ on Md

**Screenshots**
![Screen Shot 2020-07-07 at 9 28 08 AM](https://user-images.githubusercontent.com/33264095/86791110-313c6f80-c037-11ea-9ce6-f213ffe4c92a.png)
![Screen Shot 2020-07-07 at 9 40 10 AM](https://user-images.githubusercontent.com/33264095/86791163-3ef1f500-c037-11ea-8c05-d1a0a425febc.png)
<img width="987" alt="Screen Shot 2020-07-07 at 9 32 50 AM" src="https://user-images.githubusercontent.com/33264095/86791218-4c0ee400-c037-11ea-905c-cae522ab21e5.png">

**Desktop:**

**Smartphone:**
 - Device:Samsung S8 & S10e
 - OS: Android
 - Version 10&9
 
**Mapeo Version:**
 - Desktop v5.3.0 beta-1
 - Mobile v2.0.0-beta.5642,v2.1.0-RC.781-QA, v5.0.0-RC.810-QA
 
**Additional context**
Will add case by case sequence of events below

**Comment by okdistribute** [comment]
This will be fixed in the next version, got a bandaid fix here
(digidem/mapeo-core#97) and @noffle is working on another approach

**Comment by noffle** [comment]
> @noffle is working on another approach

fyi for v9, not v8

**Comment by okdistribute** [comment]
Fixes in v5.3.0 beta 2
