### ISSUE TITLE
Mapeo crashes when try to edit already filled "Single select" field

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-desktop#371]
**Describe the bug**
In Mapeo Observations screen, if you look at details of an observation that has single select fields already filled in, then if you try and edit these - or what I did was try to delete the word that was there by placing cursor at the end of the content and hitting backspace, then Mapeo screen went blank and only way I could get it back was to quit and reopen Mapeo. 

**Can you do the same thing twice?**
I did it twice
The exact steps to see the problem again.

**Expected behavior**
Would expect if you click a field where a single select option was already filled in that it would give you the different options again rather than appear to let you edit the text directly.

**Desktop:**
- version for mac
 - Version [5.3.0-beta.2]

**Comment by okdistribute** [comment]
This will be fixed by https://github.com/digidem/react-mapfilter/pull/101
