### ISSUE TITLE
Differentiated UI for unfilled and noneditable fields in observations detail

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-desktop#372]
**Describe the idea**
When you pull up details of a point in Observations screen, if the field is uneditable (eg. multiselect seems uneditable) then it appears greyed out. If the field doesn't have anything filled in yet then it also appears in grey. Can these be differentiated?

**Have you thought about what it might look like?**
Would expect them to look different, so that it was clearer which ones were simply uneditable, and which ones you could click on and edit. Maybe use different colours or fonts etc. to help with this.

**Comment by okdistribute** [comment]
All should be editable in the latest 5.3.0-beta.3, incoming!
