### ISSUE TITLE
Unexpected Behaviour / UX or UI improvement issue template

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-desktop#375]
@okdistribute @noffle @gmaclennan @jencastrodoesstuff what do you think about having, in addition to the templates for "Bug Report" and "Feature Request" a template for something like Unexpected Behaviour or UX/UI improvement. Lots of things fall under this category I think. For now I will just create them as blank issues, as they don't seem to quite fit either of the options we have in template.

It could have prompts like:

_What you currently see_

_What you would expect to see / how you would expect or prefer it to behave_

**Comment by gmaclennan** [comment]
@aliya-ryan I agree with these ideas.
