### ISSUE TITLE
Mapeo Crashed when saving edits after typing in tags box

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-desktop#378]
**Describe the bug**
Mapeo crashed - went to a blank white screen - when I was trying to save edits in Mapeo Territory view, after adding new tags in the save screen.

**Can you do the same thing twice?**
The exact steps to see the problem again.
1. Make some changes in Territory screen
2. Click on Review your changes and save them
3. In the 'All Tags' drop down, type a new tag into the text box - I added user=aliya
4. Click outside of this box - or on save - and it goes to blank white screen
--- the screen can be recovered by reloading Mapeo, but other users might not try this, and otherwise you have to quit and reopen.

**Expected behavior**
For Mapeo not to crash
Perhaps unnecessary for the tags box to be editable - and perhaps for the extra tag adding to be there at all as it doesn't seem to add anything to the data.

**Desktop:**
 - OS: iOS

**Mapeo Version:**
 - Desktop [e.g., 5.3.0-beta.2]

**Comment by okdistribute** [comment]
@aliya-ryan thanks for reporting this! One remaining question that is unclear to me, do you think we should make the tags box uneditable and/or not allow users to add an extra tag?
