### ISSUE TITLE
Mapeo 5.3.1 stays in English when Mac System language is in Spanish

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-desktop#400]
**Describe the bug**
If the system language is set as Spanish, on a mac, (restarted mac with Spanish set), and you open Mapeo, it all appears still in English.
For reference, I looked back at some earlier versions, and with v5.0.0 it appears as expected in Spanish; in v5.1.0 it already isn't working in Spanish, and it was noted during testing of 5.3.1.
I don't know if this is a bug on windows machines as well as macs.

**Can you do the same thing twice?**
@jencastrodoesstuff  experienced the same problem

**Expected behavior**
If language of system changes then language of Mapeo should change. Definitely to Spanish anyway as we have it translated.

**Desktop:**
 - OS: ios
 - Version: 10.14.6
 
**Mapeo Version:**
 - Desktop [e.g., 5.3.1]

**Comment by okdistribute** [comment]
Will be fixed in 5.4.0-beta!
