### ISSUE TITLE
Specify electron version in one place

### ISSUE THREAD

**Issue by noffle** [digidem/mapeo-desktop#41]
This version needs to be consistent for builds to work. It currently appears in:
1. `package.json` in `dependencies`
2. `package.json` in the `rebuild-leveldb` script
3. `bin/package_windows.js` as `version`
4. `bin/package_macos.js` as `version`

We ought to specify it _once_ in `package.json` in `dependencies`, and then use that as the canonical source for the leveldb rebuild script and the win/mac package scripts.

**Comment by karissa** [comment]
this will get fixed in #127
