### ISSUE TITLE
Save Report  -  button not saving PDF & wrong label

### ISSUE THREAD

**Issue by jencastrodoesstuff** [digidem/mapeo-desktop#410]
**Doesn't print or save a PDF**
A Button is no longer a print function but a save PDF function - Update label.
B. Save Prompt opens but does not save a pdf. 
C. No message indicates success or report last created date.

**Can you do the same thing twice?**
The exact steps to see the problem again.
1. From the reports view click "Print" (it doesn't mater what the filter state is.)

2. Mac save dialoge opens. Specify location. Name file, Click Save

3. go to specified location too locate saved PDF report 
4. There is no report

**Expected behavior**
A -Save PDF button says what it does
B - that a PDF is actually saved
C - After save, a message confirming save time and a location

To find the PDF in the specified location
.

**Screenshots**
<img width="1286" alt="Screen Shot 2020-08-31 at 9 25 53 PM" src="https://user-images.githubusercontent.com/33264095/91785405-567ed180-ebd3-11ea-9318-f32c11632095.png">

<img width="1072" alt="Screen Shot 2020-08-31 at 9 26 17 PM" src="https://user-images.githubusercontent.com/33264095/91785430-60a0d000-ebd3-11ea-88ff-d928bb959819.png">

<img width="903" alt="Screen Shot 2020-08-31 at 9 26 58 PM" src="https://user-images.githubusercontent.com/33264095/91785445-672f4780-ebd3-11ea-8556-dac21981e3de.png">

**Desktop:**
 - OS: iOS
 - Version: iOS 10.15.6

 
**Mapeo Version:**
 - Desktop: Md v5.4.0.beta7

**Comment by okdistribute** [comment]
![Screenshot from 2020-09-15 14-47-06](https://user-images.githubusercontent.com/633012/93268689-77622d80-f762-11ea-9140-910862b7c63e.png)

**Comment by jencastrodoesstuff** [comment]
@okdistribute  fascinating that your screen capture says save and mine says print.
v5.4.0-beta9
<img width="603" alt="Screen Shot 2020-10-08 at 2 33 58 PM" src="https://user-images.githubusercontent.com/33264095/95499485-552f8a00-0973-11eb-9784-38ec7d7da8a0.png">
