### ISSUE TITLE
PDF Reports do not work reliably when using offline styles

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#416]
**Describe the bug**
If the user has installed an offline style for the Observations view, then when trying to view the report tab, sometimes the report will get stuck in "Loading..." mode.

**Can you do the same thing twice?**
1. Install an offline map style
2. Go to the Observations view
3. Switch to the "Report" tab
4. Click through a few different filters

Eventually (for me, on MacOS) the report gets stuck on "Loading...". This does not happen when I do not have an offline style (e.g. when I am using the default Mapbox online style).

**Expected behavior**
PDF report preview should load

**Desktop:**
 - OS: MacOS
 - Version 10.15

**Mapeo Version:**
 - Desktop https://github.com/digidem/mapeo-desktop/pull/411/commits/4f5271489162b16dd5ea2961c6d7c7ecd616f7cd from https://github.com/digidem/mapeo-desktop/pull/411
 
**Additional context**
Inspecting the background process, the cause for delay is the request by the mapbox library to `http://localhost:5000/styles/default/style.json` (made from the `background.html` window). My guess that this is somehow related to the server running in the same process of where the request is made? When the `main.html` window requests the same URL it returns straight away.

**Comment by okdistribute** [comment]
weekend quick thoughts on this, if it is in fact true this is an issue because it's in the same background window -- one option would be to have the map printer be in a separate process from the http/mapeo-core process. this is also potentially useful since the map printer needs to have access to the dom right now, but the mapeo-core/mapeo-server does not.

**Comment by gmaclennan** [comment]
Yes, I agree. Also from electron 10 [there are issues](https://github.com/electron/electron/issues/18397) with running native node modules in a renderer process, so keeping most of Mapeo-core in a Node process and the static maps in its own background window is ideal.
