### ISSUE TITLE
Suddenly white screen

### ISSUE THREAD

**Issue by manynumbers** [digidem/mapeo-desktop#427]
**Describe the bug**

**Can you do the same thing twice?**
The exact steps to see the problem again.

**Expected behavior**
Just keeping on adding locations I knew, then suddenly, without any reason that I could tell, it went whtite

**Screenshots**
I am hosting further down

**Desktop:**
win 10 enterprise 64 installed today, latest update
latest firefox 80.0.1 (but I was using the app)

**Smartphone:**
no
 
**Mapeo Version:**
 - Desktop 5.3.1, confirmed
 
**Additional context**
It was, above all else, sudden. I used the functions "area" and "point" and it was my first time I experimented with some background. But I was definitively using "OpenStreet data" for a map.

Apologies for any errors I am very new at this and extremely stressed out I was procrastinating with trying a map that isnt big corporation. 

Logfile up until error plus a screenshot is at this link but I need to know the logfile can't be used to identify me, before I can hand you something like that.

#Sorry and hope I helped at all.
===================================
http://onionshare:grime-voicing@5bkn4io4kliucx27v4vboaqxfckd5qqibmp3dckpkjj76flkib5qqayd.onion

I will host very frequently the coming week. Used to be free img hosts around. Died from my money. Now they sell your data or take your money.

**Comment by rudokemper** [comment]
Hello @manynumbers, I am familiar with this bug and I expect that we resolved this in v5.4.0. If you are still interested in trying out Mapeo, I might suggest that you try again, but for now I think @ximenabb we can close this issue.
