### ISSUE TITLE
Internationalize the closing screen

### ISSUE THREAD

**Issue by okdistribute** [digidem/mapeo-desktop#429]
The closing screen will be shown if Mapeo takes too long to exit or if there is an active sync in progress. Right now it is always in spanish.
![Screenshot from 2020-09-24 13-29-55](https://user-images.githubusercontent.com/633012/94197171-3fe23800-fe6a-11ea-8b06-eb9a98fce66c.png)

**Comment by achou11** [comment]
Deferring to https://github.com/digidem/mapeo-desktop/issues/509 (same issue)
