### ISSUE TITLE
Report observation photo frame artifact

### ISSUE THREAD

**Issue by jencastrodoesstuff** [digidem/mapeo-desktop#433]
**Describe the bug**
In the PDF report one observation with multiple photos has an extra frame with no image. The observation has 4 photos but the report has 5 frames.

**Can you do the same thing twice?**
Yes
No filters. Just saving a PDF Report after sync
test 1 after Wifi sync.
test 2 after purging DB folder and syncing same data from file.

Same result

**Expected behavior**
number of photos  and number of frames in report are the same

**Screenshots**
<img width="490" alt="Screen Shot 2020-10-05 at 5 45 30 PM" src="https://user-images.githubusercontent.com/33264095/95135562-9a18ae00-0732-11eb-94b0-642fb1f49068.png">
[Report-2020_10_05-17_37_46.pdf](https://github.com/digidem/mapeo-desktop/files/5330247/Report-2020_10_05-17_37_46.pdf)

Data [syncfile](https://drive.google.com/file/d/1nkNU5L-V1RrQ0brZnR7A0Y2-RpB4gHy7/view?usp=sharing )

**Desktop:**
 - OS: Mac OS

 
**Mapeo Version:**
 - Desktop v5.4.0-beta 9

**Comment by gmaclennan** [comment]
Fix pending in #436
