### ISSUE TITLE
Export Observations as CSV

### ISSUE THREAD

**Issue by arky** [digidem/mapeo-desktop#442]
We received a request from our partners to provide an option to export observations as CSV. The rationale is that CSV are more accessible for non-GIS folks to do some basic data processing. 

For now I have suggested to use GeoJSON.io to convert geojson to CSV for the time being.

**Comment by gmaclennan** [comment]
Hi @arky, this should already be possible. If you select "Export Observations" it should open a dialog which includes the field "Data Format" where you can select CSV:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/290457/95771678-6221e580-0cb3-11eb-93f4-47fe0dcb6f11.png">

Let me know if this is not working for you.

**Comment by gmaclennan** [comment]
If this was not obvious to the user, we could think about how we could adjust the design to make it clearer. I think in general drop-down fields are not a great UX experience here, vs. being able to see all options with an explanation about what format is useful for.

**Comment by arky** [comment]
Thanks for pointing this out. I had forgotten that there was already an option to export CSV. 

I think a good solution to ensure we have proper documentation before investing in UI refresh. 

https://docs.mapeo.app/?q=CSV
