### ISSUE TITLE
"Zoom to data" in Territory view doesn't zoom to observations

### ISSUE THREAD

**Issue by rudokemper** [digidem/mapeo-desktop#446]
**Describe the bug**
It seems that currently, the "Zoom to data" option (View menu) for the `Territory` view is not zooming to points that were collected as Observations using Mapeo Mobile. When you have an instance of Mapeo that has Observations loaded in, but nothing drawn natively in Territory, clicking on "Zoom to data" does nothing.

**Can you do the same thing twice?**
The exact steps to see the problem again.
1. Start with an empty instance of Mapeo Desktop
2. Collect observations on Mapeo Mobile
3. Sync those observations with Mapeo Desktop
4. Ensure that the observations have been synced in the `Observations` view in Mapeo Desktop
5. Navigate to the `Territory` view.
6. Select `View` -> "Zoom to Data".
7. Nothing happens.

**Expected behavior**
I would expect "Zoom to data" to zoom to the maximum extent of all data, both observations as well as data mapped natively in the Territory view.

**Screenshots**
![image](https://user-images.githubusercontent.com/31662219/96002020-aa9de800-0e06-11eb-8f78-c2ac612fded9.png)
This singular data point (collected as Observation) is not zoomed to when doing the above behavior.

**Desktop:**
 - OS: Windows 10 Enterprise
 
**Mapeo Version:**
 - Desktop 5.3.1
 - Mobile 5.0.3.879

**Comment by gmaclennan** [comment]
Fixed in #475
