### ISSUE TITLE
Enable Locale switching for Th/Vi/Km

### ISSUE THREAD

**Issue by arky** [digidem/mapeo-desktop#447]
<details>
<summary>
Please kindly include ability to switch mapeo-desktop Thai(th), Vietnamese(vi) and Khmer (km). 

We are planning to actively translating mapeo-desktop into these language starting with Thai. It would be great to have an ability to switch into these languages so we could start testing the builds. 

https://github.com/digidem/mapeo-desktop/tree/master/messages/main

https://github.com/digidem/mapeo-desktop/blob/70033f89be9ff35286eb77d972bbf5b8865781bd/src/main/i18n.js#L6

</summary>

![Thai-Mapeo](https://user-images.githubusercontent.com/808895/96026088-40298e00-0e80-11eb-8bf2-6e336281e9bb.png)

</details>

**Comment by okdistribute** [comment]
fixed in 945de46
