### ISSUE TITLE
Preventing Windows from prompting about security risks about downloading MAPEO

### ISSUE THREAD

**Issue by rudokemper** [digidem/mapeo-desktop#458]
**Describe the idea**
Currently, when downloading MAPEO on Windows, the browser prompts the user with a notification that MAPEO may harm the system, and the way to continue downloading MAPEO anyway is a little obscure -- one has to click the link "Conservar de todos modos" (Save Anyway) in the screenshot below.

![Windows install](https://user-images.githubusercontent.com/31662219/101651244-d9050180-3a0a-11eb-8af0-fb758355d782.PNG)

Could there be a way to update our certificate that we use to sign Mapeo, to guarantee trust by Windows?  

**What's your role? Where and how do you currently use the application?**
I'm on the programs team with Digital Democracy, and I recently encountered this issue with one of our partners, who encountered the issue. (The above screenshot is from their laptop directly.)

**Comment by ximenabb** [comment]
Note to look into in Jan/Feb 2022
