### ISSUE TITLE
Migrate to TypeScript via JSDocs

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#467]
**Describe the idea**
Currently we use [Flow](https://flow.org) for type checking some of our frontend code. It definitely adds overhead for initially writing code, but it makes maintenance and collaboration with other developers on the same codebase a lot easier. However, TypeScript is far more popular than Flow, more people know TypeScript, there are more resources online, and more libraries have published types in TypeScript.

We don't currently typecheck any of our backend code, because we have no build step for the backend (which is necessary for Flow, since it needs to be compiled to JavaScript.

For a while now I have been writing my code using [TypeScript via JSDocs](https://www.typescriptlang.org/docs/handbook/intro-to-js-ts.html). I've found it really nice because the code can run without any build step, and you can understand the code without understanding TypeScript. TypeScript will only check files that start with a `// @ts-check` comment, and all types are written as comments, in a format that is very close to [JSDoc](https://jsdoc.app), which has the consequence of also nicely documenting all code. 

**Implementation plan**
I have now configured TypeScript for Mapeo Desktop and you can typecheck the code via `npm run type`, or setup integration with your Editor (I use VS Code). To start typechecking any file with Typescript, add `// @ts-check` as the first line of the file, and add JSDoc comments. We can do this on a file-by-file basis and gradually remove Flow. Both type systems can exist at the same time for now.

**Comment by noffle** [comment]
This sounds really nice. Where can I find some of your existing code
that does this? I did an org-wide github search for "ts-check" but
didn't turn up anything.

**Comment by noffle** [comment]
I didn't see this on `master`. Is it on another branch?

**Comment by gmaclennan** [comment]
My apologies, yes, this hasn't been merged yet: https://github.com/digidem/mapeo-desktop/pull/465

**Comment by ErikSin** [comment]
I am going to close this as this is something we are addressing currently, and will be addressing this for a long time, so it does not seem necessary to have this on our issues.
