### ISSUE TITLE
WiFi signal component causing slowdown and crashes

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#469]
**Describe the bug**
Our bug reporting service (Bugsnag) has been showing multiple error reports from the SyncBarApp component, caused by `node-wifi` throwing an error when calling `getCurrentConnections()`: https://app.bugsnag.com/digital-democracy/mapeo-desktop/errors/5f21e05102661d00179a027d?filters[event.since][0]=30d&filters[error.status][0]=open

The errors are thrown multiple times, and Bugsnag eventually reports that the error notification quota is exceeded.

On further investigation, this seems due to the fact that `wifi.getCurrentConnections()` is called every 2 seconds, even if it throws an error, so the error is thrown (and reported to Bugsnag) every 2 seconds.

In addition, the Sync tab view is never unmounted, so this interval continues to run in the background when the user is on other screens in the app.

In addition, when testing on a MacOS, I discovered that this module causes a massive slowdown of the app, with each call to `wifi.getCurrentConnections()` locking up the render process for ~2 seconds every time it runs (interactions with the app stop working during this time). This only happens with the signed production build, not with the dev build. This appears to be due to an unresolved bug in Electron: https://github.com/electron/electron/issues/26143. This in turn is due to an unresolved bug in libuv: https://github.com/electron/electron/issues/26143

This is because under the hood, [`node-wifi` calls `child_process.execFile`](https://github.com/friedrith/node-wifi/blob/master/src/macOS/current-connections/command.js).

This also appears to be the cause of crashes when closing the app on MacOS

**Can you do the same thing twice?**
It appears to be called by `node-wifi` not working on some user devices, and is reproducible using the signed production build on MacOS Big Sur.

**Expected behavior**
No slow down and no crash.

**Screenshots**
<img width="612" alt="image" src="https://user-images.githubusercontent.com/290457/120846163-a5460700-c569-11eb-8cde-e6229bd404dd.png">

**Desktop:**
 - OS: MacOS
 - Version Big Sur 11.3

**Smartphone:**
N/A
 
**Mapeo Version:**
 - Desktop 5.4.0-beta.11
 - Mobile N/A

**Proposed solution**
- Remove node-wifi code for now, due to slowdown on MacOS and potential crashes on other OS
- Unmount the sync tab when switching tabs, to reduce resource use.

**Comment by jencastrodoesstuff** [comment]
The solutions you propose make sense. It's not the best UX but since finding the Wifi connection name on a desktop OS isn't too hard and this is an Md user experience I think that compromise makes sense right now.
