### ISSUE TITLE
Cannot run Mapeo Desktop on Mac

### ISSUE THREAD

**Issue by saowalakj** [digidem/mapeo-desktop#499]
After installing Mapeo on the Mac, the error messages show:

<img width="254" alt="Screen Shot 2564-07-16 at 13 42 33" src="https://user-images.githubusercontent.com/38714949/125909095-81a8ae1f-4b69-4d8d-9347-c6cb03066430.png">
 displays:

<img width="257" alt="Screen Shot 2564-07-16 at 13 35 39" src="https://user-images.githubusercontent.com/38714949/125909072-f963736e-d51e-42a2-89db-d817978f56e4.png">

It happens both when downloading from https://www.digital-democracy.org/mapeo/download/ and https://github.com/digidem/mapeo-desktop/releases/tag/v5.4.0-beta.14.

**Comment by achou11** [comment]
hi @saowalakj! currently publishing a new beta release that should fix this and will update this comment to point to it when that's ready. apologies for the inconvenience!

**Comment by arky** [comment]
@saowalakj Can you please test this one and see if you are able to install and run mapeo-desktop?

https://github.com/digidem/mapeo-desktop/suites/3258979139/artifacts/75815755
