### ISSUE TITLE
Correct spelling of 'Installer' in build output filenames

### ISSUE THREAD

**Issue by emreiser** [digidem/mapeo-desktop#508]
**Describe the bug**
We are currently naming build output files for all operating systems with the prefix "Installar_Mapeo_v$". Change prefix to "Installer_Mapeo_v$" in [builder config](https://github.com/digidem/mapeo-desktop/blob/master/builder.config.js) and update references in CONTRIBUTING.md (and index.js?)

**Comment by achou11** [comment]
Based on [context](https://github.com/digidem/mapeo-desktop/pull/617#issuecomment-969043785) provided by @gmaclennan , leaning towards changing the name to `Install`
