### ISSUE TITLE
(Front) Make header text in closing.html a translatable string

### ISSUE THREAD

**Issue by emreiser** [digidem/mapeo-desktop#509]
**Describe the bug**
The text displayed when quitting Mapeo is currently hard-coded and not available as a translatable string. See: https://github.com/digidem/mapeo-desktop/blob/master/static/closing.html#L46

<img width="597" alt="Captura de Tela 2021-07-21 às 1 50 07 PM" src="https://user-images.githubusercontent.com/3493841/126536096-ee1e8ee0-b09c-4c7d-b920-c718d85bea07.png">
 
**Mapeo Version:**
 - Desktop 5.4.0-beta.15 

Points: 8

**Comment by bthrall** [comment]
This looks like a duplicate of #429

**Comment by achou11** [comment]
Ah yes you're right @bthrall. Thanks for noting! We'll close the other one and defer to this one :)
