### ISSUE TITLE
(Front) Color code dots on map

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-desktop#615]
**Description:**
Color code dots on map by category or thematic category group. Currently, Mapeo Desktop Observations data renders as red dots, exclusively. (And the same is true of Mapeo Mobile, where the data renders as orange dots.)

Our partners and third-party users of Mapeo frequently lament this behavior, and request that this be changed to a more helpful symbology, enabling them to make better sense of the data in a visual way.
[Full discussion here](https://www.notion.so/digidem/Md-Observations-and-Mapeo-Mobile-data-symbology-5bec31ed5be04121a9c67d4a949696bf)

An interim proposal from Programs is:
- Add an optional `color` field to `preset.json` files to determine the color of a category's dot.
    - Don't change anything about how we are rendering clustered dots at a distance.
    - if no color is specified, fallback to default color used at the moment

**Issued logged :** [https://www.notion.so/digidem/Color-code-dots-on-map-by-category-or-thematic-category-group-22c6e67878a24350806875460d7397ab](url)

**Points :** 13

**Comment by achou11** [comment]
> The intention is to apply a color to all categories within a thematic group, rather than assigning a unique color to every category. (The proposed updated config uses only 8 groups - ie. natural elements: green, water: blue, threats: red, cultural: yellow, etc.) 

@emreiser are the groups mentioned here detailed anywhere?
