### ISSUE TITLE
Add ability to review a list of recent changes.

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-desktop#62]
Should have the option eventually of reviewing the changes made - and seeing who made the changes, so that someone can check them and accept or reject them if they are incorrect for some reason (eg. people making changes to areas outside their community area or changes to river-data)

**Initially want to just see the changes on the map (not just in a list)**

Later (have created other issue attached to later milestone) want to see who made change, revert change, look at changes to a specific area.

**Comment by noffle** [comment]
@aliya-ryan Could you expand on this a bit? I'm not sure what you mean by wanting to see the changes on the map.
