### ISSUE TITLE
Can't start app from ZIP on MacOS

### ISSUE THREAD

**Issue by achou11** [digidem/mapeo-desktop#625]
**Describe the bug**
Installing Mapeo via the `zip` file prevents it from being able to open on MacOS.

**Can you do the same thing twice?**

1. If you're on a Mac, you can go to the [downloads page](https://www.digital-democracy.org/mapeo/download/). Otherwise, install from https://github.com/digidem/mapeo-desktop/releases/download/v5.4.0/Installar_Mapeo_v5.4.0_mac.zip
2. Go through installation steps
3. Try to open application
4. See native error dialog

**Expected behavior**
You should be able to open the application after installation

**Screenshots**
![image](https://user-images.githubusercontent.com/18542095/142044444-f161a57c-1cc6-417b-8d03-f2cd376a7f5d.png)

**Desktop:**
 - OS: MacOS Big Sur
 - Version: 11.6.1
 
**Mapeo Version:**
 - Desktop 5.4.0

**Additional context:**
Looks like the version of `electron-builder` we're using has a relevant issue that was fixed in a later version. Hopefully, just upgrading versions will resolve this issue.
- original issue: https://github.com/electron-userland/electron-builder/issues/4299
- release with fix: https://github.com/electron-userland/electron-builder/releases/tag/v22.11.9

**Comment by achou11** [comment]
Looks like this is not going to be trivial. `electron-builder` introduced a breaking change in `v22.11.4` that requires node >14. Not sure what kind of work is needed to get our stack to be compatible with 14, but my guess is that it won't be straightforward since the problematic deps run deep 😞

**Comment by gmaclennan** [comment]
We can stick with the same version of electron right? If we don't need to change electron version, then the Node runtime version will remain the same. I am ok with updating the node version for dev to v14, it should not affect the runtime. I had just kept it the same as the runtime for making running tests easier (tests can run in the same node env as the build process). We don't actually run any backend unit or integration tests within the Mapeo Desktop repo at the moment, so that's ok too.

**Comment by achou11** [comment]
@gmaclennan yep that's correct! Just thought it'd be ideal to stick with the node version that the electron runtime has for the reasons you outlined, but if we're not taking advantage of that in development, then yeah we can go ahead and update the dev environment 👍

**Comment by achou11** [comment]
PR with changes based on above discussion here: https://github.com/digidem/mapeo-desktop/pull/629
