### ISSUE TITLE
Add background layer of rendered maps with Mapbox-gl

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-desktop#63]
So that those working on the map can see the Mapbox styled map underneath the data they are editing, with the symbols etc. 

Later on (September Milestone): Add editing functionality to mapbox-gl layer - don’t render everything in SVG.

**Comment by aliya-ryan** [comment]
Later on (September Milestone): Add editing functionality to mapbox-gl layer - don’t render everything in SVG.

**Comment by ErikSin** [comment]
@aliya-ryan I'm going to close this, if this is still something you would like do you mind adding it to the tech priorities list!
