### ISSUE TITLE
chore: Test Github Action running on macos-11

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#630]
Our Github actions (for building Mapeo) currently run on the `macos-latest` virtual environment, which is currently MacOS 10.15. From [December 13th the latest image will change to MacOS 11](https://github.com/actions/virtual-environments/issues/4060). Before this happens we should either:

1. Create a PR with the image manually set to `macos-11` and check if it builds ok, and merge if so.
2. Set the image to `macos-10.15`, so that we keep our existing behaviour after Dec 13th. MacOS 10.15 continues to be supported by Github.

**Comment by achou11** [comment]
would be interesting to also update `electron-notarize` and try using the notary tool that comes with MacOS 11 (see `tool` [option](https://github.com/electron/electron-notarize#method-notarizeopts-promisevoid))
