### ISSUE TITLE
Icon for Mapeo Installer disk image

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-desktop#76]
The icon for Mapeo Installer Disk Image (dmg) when mounted on Mac is the same as the application icon so it is confusing to know which one to delete after the installation is complete.

**Comment by noffle** [comment]
Is there another icon that we can use for the dmg?

**Comment by noffle** [comment]
I can whip up an edit to the icon in GIMP to make it clear it's an installer and not the application.
