### ISSUE TITLE
Integrate tile layers into app in UserData folder

### ISSUE THREAD

**Issue by mcplanner** [digidem/mapeo-desktop#8]

**Comment by gmaclennan** [comment]
I have created tile layers, see [#12](https://github.com/digidem/ecuador-map-editor/issues/12#issuecomment-195166304) for more info.

@substack I think we need to manage these outside the application bundle. Can we point to an `imagery.json` and folders of tiles all under `UserData/tiles` served under `locahost:port/tiles`? For now, I can manually place tiles and imagery.json in the `UserData/tiles` folder, later we can set up a UI for adding and managing tilesets.

**Comment by gmaclennan** [comment]
So to do this we need to dynamically load imagery.json at runtime from `UserData/tiles/imagery.json` but we should use the iD default first before that loads.
