### ISSUE TITLE
Allow manually changing of UI language

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#81]
Currently Mapeo respects the operating system language for the user-interface language. It would be useful to be able to manually override this setting, because the presets we use for each project area are normally only in one language (currently Spanish), and when using these presets from a computer in en-US then strings appear as raw ids. The current work-around is to change the operating system language, but this is tedious.

We need some kind of settings pane to change the language.

**Comment by DenisCarriere** [comment]
There's a library [`os-locales`](https://github.com/sindresorhus/os-locale) which detects which language the OS is in, that way the application is automatically changed based on the users OS language preferences. Pairing that with a manual language override would also be good 👍

**Comment by gmaclennan** [comment]
thanks @DenisCarriere this will be useful. Also tracking internationalization in https://github.com/digidem/mapeo-desktop/issues/80

**Comment by DenisCarriere** [comment]
👍 Thankfully my spanish isn't too bad and I was able to use Mapeo without too much trouble :)

**Comment by karissa** [comment]
I wonder if this is still an issue with the new version of id? https://github.com/digidem/mapeo-desktop/pull/107

**Comment by karissa** [comment]
Just tried our newest iD fork with a French system language using the jungle presets, and it looks like it's using the English names 
<img width="903" alt="screen shot 2018-03-15 at 10 42 55 pm" src="https://user-images.githubusercontent.com/633012/37504167-448ecbe8-28a2-11e8-9596-0f949e386d7d.png">

**Comment by gmaclennan** [comment]
I think we still need this, particularly if we work in languages (i.e. Waorani) which are not operating system languages. Right now iD picks up the language from the operating system, or in v1 (don't know if it's the same in v2) you can pass a URL param `?lang=`. I think it would be good to have a menu option for this.
