### ISSUE TITLE
Avoiding duplicate imports

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#88]
Putting this idea here so we don't forget it later.

At some point we need an easy way to import data into Mapeo. However, we need to avoid filling the database with duplicate data - it is quite likely that users could import the same data twice.

If a user imports exactly the same feature twice I think we should just silently ignore any duplicates. At a hyperlog level duplicate features would have the same hash, however when we create a new feature we generate a random OSM id, which gives it a different hash in hyperlog.

I see two possible strategies:

1. Keep a list of hashes of imported features, and test against them on import. Would not work with disconnected imports.

2. For imports, use the hash of the imported data as the OSM ID of the feature. This would mean that every time you import the same feature it would have the same hash in hyperlog.

For (2) would that cause any issues with hyperkv or the underlying hyperlog? e.g. we would be calling osm.put() twice with the same`id` and value.

**Comment by noffle** [comment]
I think if our import is anything but hyperlog-level replication of a leveldb, things will get messy. The data itself may be deduplicated, but the export would need to track full history (node links) exactly as the hyperlog does, or else results will be inconsistent with what you might expect.

**Comment by karissa** [comment]
I believe this is solved with the developments over the past few months with handling `observations` and converting observations to features.
