### ISSUE TITLE
Show progress whilst indexes are being built

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#90]
This is not high-priority and it is rare that a user will experience this.

If you start Mapeo with a large dataset when the index is empty/behind it takes a long time for any data to appear, with no indication of what is happening or whether data will appear in the future.

we should show the user some kind of visual indication when indexing is being done, so that they know data is "on its way"

**Comment by noffle** [comment]
Related: https://github.com/digidem/mapeo-desktop/issues/91

**Comment by karissa** [comment]
there is some existing code for this but it's not enabled in the UI currently AFAIK after the update to kappa-core
