### ISSUE TITLE
Can not sync after loading new configuration until restart

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-desktop#95]
I opened Mapeo, having changed the data set it pointed to (Wao rather than Cofan), I then imported the correct settings file (configuration) for the data and zoomed to data - it showed me the correct data without having to restart mapeo.

However when I tried to sync it with the latest update from the field it would not recognise the file, only when I closed Mapeo and reopened it did it recognise it. So it seems like you don't need to restart Mapeo after importing a new config if you are just using the data as is, but if syncing you do need to.

**Comment by noffle** [comment]
This should have been fixed in 1.7.0 (via 412e0c).
