### ISSUE TITLE
Mapeo crashes when trying to export to geojson

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-desktop#98]
Using version 1.7, with the Wao data, when I try to export via the menu command it lets me choose a file location and creates a (subsequently empty, 0b) file but then Mapeo crashes with the notice "can not read property of '0' undefined" (same notice I think when we used to try to save after deleting the ghost points). 

<img width="548" alt="screen shot 2017-05-08 at 09 04 53" src="https://cloud.githubusercontent.com/assets/21277147/25795562/cf707d62-33cd-11e7-9c47-c00a5ea0d957.png">

**Comment by aliya-ryan** [comment]
I just updated to V1.8 and problem remains.

**Comment by noffle** [comment]
Found the problem! Thanks for reporting this. Fixed in [1.9.0](https://github.com/digidem/mapeo-desktop/releases/tag/v1.9.3).
